### PR TITLE
Adding language pt_br

### PR DESCRIPTION
**Pull request by alexandrefernandesjs**
Adding language pt_br and starting translation of functions and menus.

### CODE REVIEW

**Comment by gepd** [comment]
muito obrigado @alexandrefernandesjs !

**Comment by gepd** [comment]
I've just noted it's not complete :/

**Comment by alexandrefernandesjs** [comment]
I'm translating everything tomorrow I'll send one more part I hope the rest of the file.

**Comment by gepd** [comment]
thanks very much!

**Pull request merged**
